name: Create Droplet

on:
  schedule:
    # Run at 8:00 PM IST (14:30 AM UTC)
    - cron: "16 6 * * *"

jobs:
  create_droplet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2

      - name: Initialize Terraform
        run: terraform init
      
      - name: plan terraform
        run: terraform plan none

      - name: Create Terraform (Create Droplet)
        run: terraform apply none -auto-approve -var="digitalocean_token=${{ secrets.DIGITALOCEAN_TOKEN }}"
