name: Terraform Droplet Lifecycle

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    # Run at 11:00 AM IST (5:30 AM UTC)
    - cron: "45 8 * * *"
    # Run at 12:00 PM IST (6:30 AM UTC)

jobs:
  create_droplet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.2
    
    - name: Initialize Terraform
      run: terraform init
    
    - name: Create Droplet
      run: terraform apply -auto-approve -var="digitalocean_token=${{ secrets.DIGITALOCEAN_TOKEN }}"