name: Terraform Droplet Lifecycle

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    # Run at 8:00 AM IST (2:15 AM UTC)
    - cron: "25 10 * * *"
    # Run at 12:00 PM IST (6:30 AM UTC)

jobs:
  create_droplet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.2
    
    - name: Initialize Terraform
      run: terraform init

    # Start Cronitor monitoring
    - name: Start Cronitor Heartbeat
      run: curl https://cronitor.link/${{ secrets.CRONITOR_API_KEY }}/run

    - name: Create Droplet
      run: terraform apply -auto-approve -var="digitalocean_token=${{ secrets.DIGITALOCEAN_TOKEN }}"

    # Complete Cronitor monitoring after successful execution
    - name: Complete Cronitor Heartbeat
      if: success()
      run: curl https://cronitor.link/${{ secrets.CRONITOR_API_KEY }}/complete

    # Fail Cronitor monitoring if the workflow fails
    - name: Fail Cronitor Heartbeat
      if: failure()
      run: curl https://cronitor.link/${{ secrets.CRONITOR_API_KEY }}/fail
