# # name: Create Droplet

# # on:
# #   schedule:
# #     # Run at 8:00 PM IST (14:30 AM UTC)
# #     - cron: "35 7 * * *"

# # jobs:
# #   create_droplet:
# #     runs-on: ubuntu-latest

# #     steps:
# #       - name: Checkout Code
# #         uses: actions/checkout@v3

# #       - name: Install Terraform
# #         uses: hashicorp/setup-terraform@v2
# #         with:
# #           terraform_version: 1.5.2

# #       - name: Initialize Terraform
# #         run: terraform init
      
# #       - name: plan terraform
# #         run: terraform plan -out none -var="digitalocean_token=${{ secrets.DIGITALOCEAN_TOKEN }}"

# #       - name: Create Terraform (Create Droplet)
# #         run: terraform apply -auto-approve -var="digitalocean_token=${{ secrets.DIGITALOCEAN_TOKEN }}"
# name: Terraform Apply

# on:  # Adjust the schedule as needed (e.g., daily at midnight)
#   workflow_dispatch:  # Allows manual triggering of the workflow

# jobs:
#   terraform:
#     runs-on: self-hosted

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v2
#         # with:
#         #   terraform_version: 1.3.5  # Adjust version as needed

#       - name: Terraform Init
#         run: terraform init
#         # env:
#         #   TF_TOKEN_app: ${{ secrets.TERRAFORM_API_TOKEN }}  # Authenticate with Terraform Cloud

#       - name: Terraform Plan
#         run: terraform plan -out=tfplan

#       - name: Terraform Apply
#         run: terraform apply -auto-approve tfplan

name: Terraform Apply

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  terraform:
    name: 'Terraform Deployment'
    runs-on: self-hosted
    
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_API_TOKEN }}  # Terraform Cloud API token
      TF_VAR_digitalocean_token: ${{ secrets.DIGITALOCEAN_TOKEN }}  # Note the variable name change
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
        env:
          TF_LOG: INFO

      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR_digitalocean_token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Terraform Appddly
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        env:
          TF_VAR_digitalocean_token: ${{ secrets.DIGITALOCEAN_TOKEN }}