# name: Terraform Destroy

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: '50 7 * * *'

# jobs:
#   terraform-destroy:
#     name: 'Terraform Destroy'
#     runs-on: ubuntu-latest
    
#     env:
#       TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_API_TOKEN }}  # Terraform Cloud API token
#       TF_VAR_digitalocean_token: ${{ secrets.TF_VAR_digitalocean_token }}  # DigitalOcean API token
    
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2

#       - name: Terraform Init
#         run: terraform init
#         env:
#           TF_LOG: INFO



#       - name: Terraform Destroy
#         if: github.ref == 'refs/heads/main'  # Runs only on the main branch
#         run: terraform destroy -auto-approve

name: Terraform Cloud Destroy

on:
  schedule:
    - cron: '25 9 * * *'  
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: upload
        with:
          workspace: "Jackk-1"
          directory: "."
        env:
          TF_CLOUD_ORGANIZATION: "your-org-name"
          TF_API_TOKEN: "${{ secrets.TERRAFORM_API_TOKEN }}"

      - name: Create Destroy Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: destroy_run
        with:
          workspace: "Jackk-1"
          configuration_version: "${{ steps.upload.outputs.configuration_version_id }}"
          
          # is-destroy: true # This flag ensures the run is a destroy run
        env:
          TF_CLOUD_ORGANIZATION: "jackkkk"
          TF_API_TOKEN: "${{ secrets.TERRAFORM_API_TOKEN }}"

      - name: Apply Destroy Run
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
        if: fromJSON(steps.destroy_run.outputs.payload).data.attributes.actions.IsConfirmable
        with:
          run: "${{ steps.destroy_run.outputs.run_id }}"
          comment: "Infrastructure destroyed via GitHub Actions"
        env:
          TF_CLOUD_ORGANIZATION: "jackkkk"
          TF_API_TOKEN: "${{ secrets.TERRAFORM_API_TOKEN }}"
