name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: self-hosted
    
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_API_TOKEN }}  # Terraform Cloud API token
      TF_VAR_digitalocean_token: ${{ secrets.TF_VAR_digitalocean_token }}  # DigitalOcean API token
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        env:
          TF_LOG: INFO

      - name: Terraform Destroy
        if: github.ref == 'refs/heads/main'  # Runs only on the main branch
        run: terraform destroy -auto-approve
