# # name: Destroy Droplet

# # on:
# #   schedule:
# #     # Run at 8:00 PM IST (14:30 AM UTC)
# #     - cron: "50 7 * * *"

# # jobs:
# #   destroy_droplet:
# #     runs-on: ubuntu-latest

# #     steps:
# #       - name: Checkout Code
# #         uses: actions/checkout@v3

# #       - name: Install Terraform
# #         uses: hashicorp/setup-terraform@v2
# #         with:
# #           terraform_version: 1.5.2

# #       - name: Initialize Terraform
# #         run: terraform init

# #       - name: Destroy Terraform (Destroy Droplet)
# #         run: terraform destroy -auto-approve -var="digitalocean_token=${{ secrets.DIGITALOCEAN_TOKEN }}"
# name: Terraform Destroy

# on:
#   schedule:
#     - cron: '05 5 * * *'  # Adjust the schedule as needed
#   workflow_dispatch:  # Allows manual triggering of the workflow

# jobs:
#   terraform:
#     runs-on: self-hosted

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: 1.3.5  # Adjust version as needed

#       # - name: Terraform Init
#       #   run: terraform init
#       #   env:
#       #     TF_TOKEN_app: ${{ secrets.TERRAFORM_API_TOKEN }}  # Authenticate with Terraform Cloud

#       - name: Terraform Destroy
#         run: terraform destroy -auto-approve
